workflows:
  android-build:
    name: Android Build
    environment:
      java: 17
    scripts:
      - name: Build APK with system Gradle
        script: |
          gradle assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
